FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime

ENV PYTERRIER_VERSION='5.7'
ENV PYTERRIER_HELPER_VERSION='0.0.7'

COPY requirements.txt /workspace/

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y git openjdk-11-jdk git-lfs  \
	&& pip3 install -r /workspace/requirements.txt \
	&& python3 -c "import pyterrier as pt; pt.init(version='${PYTERRIER_VERSION}', helper_version='${PYTERRIER_HELPER_VERSION}');" \
	&& python3 -c "import pyterrier as pt; pt.init(version='${PYTERRIER_VERSION}', helper_version='${PYTERRIER_HELPER_VERSION}', boot_packages=['com.github.terrierteam:terrier-prf:-SNAPSHOT']);"

ENV PYTHONPATH=/workspace

RUN git clone https://huggingface.co/naver/splade-cocondenser-ensembledistil /workspace/splade-cocondenser-ensembledistil \
	&& cd /workspace/splade-cocondenser-ensembledistil \
	&& git lfs install \
	&& git lfs pull \

